name: parkit_app
description: "Aplicación de estacionamiento compartido en Argentina"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  provider: ^6.0.5
  
  # Backend & Database
  supabase_flutter: ^1.4.0
  
  # Maps & Location
  google_maps_flutter: ^2.2.0
  geolocator: ^10.1.0
  
  # Sensors
  sensors_plus: ^4.0.2
  
  # Notifications
  flutter_local_notifications: ^17.2.2
  
  # UI & Animations
  cupertino_icons: ^1.0.6
  animate_do: ^3.0.2
  
  # HTTP & URL
  http: ^1.1.0
  url_launcher: ^6.2.1
  
  # Permissions
  permission_handler: ^11.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - .env
    
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Bold.ttf
          weight: 700 